name: Build Sonde API Docker Image
on:
  workflow_dispatch:
jobs:
  copy-to-branches:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:${{env.DATABASE_PORT}}
        volumes:
          - ${{env.DATABASE_INIT}}:/docker-entrypoint-initdb.d/init.sql   
        options: >-
          --health-cmd pg_isready
          --health-internal 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build docker image
        run: docker build -f sonde.Dockerfile .
